version: '2'
services:
  app:
    environment:
      - DB_NAME=mpesa_api_dev_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.development
    build: .
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/usr/src/app
    ports:
      - 8090:80
    links:
      - db
      - rabbitmq

  worker:
    environment:
      - DB_NAME=mpesa_api_dev_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=config.settings.development
    build: .
    command: ./celery.sh
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./:/usr/src/app
    links:
      - db
      - rabbitmq
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=mpesa_api_dev_db
      - POSTGRES_PASSWORD=root
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: gonkulatorlabs/rabbitmq:3.6.1 #this has management plugin enabled
    ports:
      - 15672:15672
      - 5671:5671
      - 5672:5672
